### ISSUE TITLE
GestureDetector in ListView is not working

### ISSUE THREAD

**Issue by JohannesKaufmann** [mcrovero/rubber#5] opened 2019-01-11 18:20 UTC
**Describe the bug**
I have a `ListView` with items similar to the [scroll example](https://github.com/mcrovero/rubber/blob/master/example/lib/scroll.dart) (which is now working really great by the way 👍). Every item is wrapped in a `GestureDetector` that is listening for `onTap`.

There are currently three problems:
- The taps are oftentimes not regognized.
- If `onTap` is successfully called, the sheet jumps around.
- There is also sometimes the following message appearing in the console
```
flutter: ══╡ EXCEPTION CAUGHT BY GESTURE ╞═══════
flutter: The following assertion was thrown while handling a gesture:
flutter: 'package:rubber/src/bottom_sheet.dart': Failed assertion: line 149 pos 12: '_hold == null': is not
flutter: true.
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #2      _RubberBottomSheetState._onVerticalDragDown (package:rubber/src/bottom_sheet.dart:149:12)
flutter: #3      DragGestureRecognizer.addPointer.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:123:46)
flutter: #4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:102:24)
flutter: #5      DragGestureRecognizer.addPointer (package:flutter/src/gestures/monodrag.dart:123:9)
flutter: #6      RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:643:18)
flutter: #7      RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:2500:14)
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:158:22)
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:138:7)
flutter: #10     _WidgetsFlutterBinding&BindingBase&GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:101:7)
flutter: #11     _WidgetsFlutterBinding&BindingBase&GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:85:7)
flutter: #12     _invoke1 (dart:ui/hooks.dart:168:13)
flutter: #13     _dispatchPointerDataPacket (dart:ui/hooks.dart:122:5)
flutter: (elided 2 frames from class _AssertionError)
flutter:
flutter: Handler: onDown
flutter: Recognizer:
flutter:   VerticalDragGestureRecognizer#d7641(debugOwner: GestureDetector)
flutter: ═══════
```

**Expected behavior**
I expect that "normal" interactions like onTap are handled by the widgets inside of the modal.

**Comment by mcrovero** [comment] 2019-01-12 02:13
Thanks, really appreciated!
Check the latest version, it should be fixed.

**Comment by JohannesKaufmann** [comment] 2019-01-12 08:46
Great, that was fast! Taps are now properly recognized and the warning is not appearing anymore.

But as soon as it's "expanded" and an item is tapped, it is jumping: The list is animated to a position further up and then animated back to the "expanded" position.

I have two detectors:
- a `GestureDetector` wrapping the whole item.
- a `TapGestureRecognizer`inside a TextSpan. It it inside the `GestureDetector` and only fills a small amount of space.

What's weird is that when the `TapGestureRecognizer` detects a `onTap` the list is not jumping. It only happens with the `GestureDetector` (it's probably due to it's size). And when the sheet is not fully expanded that jumping does not appear at all.

**Comment by mcrovero** [comment] 2019-01-12 13:34
I can't reproduce the error, could you please share the skeleton of your widgets?

**Comment by JohannesKaufmann** [comment] 2019-01-13 12:12
I just another look at my code. I still had a `_controller.launchTo(AnimationState.half_expanded);` in the `onTap`. Sorry that was my fault 😂.

So the bug is actually that `launchTo` only works for animating upwards (collapsed -> half_expanded -> expanded). And not the other way around (for example collapsing it again). Sorry for wasting your time...

**Comment by mcrovero** [comment] 2019-01-24 22:55
No problem 😄 
Thanks for your help!

**Closed by mcrovero** 2019-01-24 22:55 UTC

**Comment by LcTwisk** [comment] 2019-05-19 20:13
I'm facing the same problem where taps are not always recognised by the `GestureDetector` that's used inside a ListView.
I'm currently on: `rubber: ^0.3.2`

I'll prepare an example project so you can reproduce it ;)
